### ISSUE TITLE
Move keyword/tracking code from index_twitter_stream.py into a separate input file

### ISSUE THREAD

**Issue by hadoopjax** [Data4Democracy/discursive#2]
Rather than having the tracking topics we want to use against the Twitter streaming API stored in our codebase let's move them to an input file. So, as a user, I can point to a file (i.e. on S3 or locally) to use as a source for my keywords! 

* Bonus points if you want to move the Tweet counter (StreamListener self.limit) and any Elasticsearch configs to a user-managed config file!

**Comment by jbrambleDC** [comment]
I am going to jump on this. should we take in the file as a sys.argv?

**Comment by jbrambleDC** [comment]
This can be closed!

**Comment by hadoopjax** [comment]
Yay! thanks @jbrambleDC
