### ISSUE TITLE
Setup cron ability in Docker container: discursive-graph-data branch

### ISSUE THREAD

**Issue by hadoopjax** [Data4Democracy/discursive#25]
Having recently "Dockerized" the Twitter collection process, one piece we're missing is the ability to run the Twitter collection from _within_ the Docker container on a schedule (i.e. using cron). The OS is Alpine Linux, and here's [a good example of what we're trying to do.](https://gist.github.com/andyshinn/3ae01fa13cb64c9d36e7) Check out the branch [here.](https://github.com/Data4Democracy/discursive/tree/discursive-graph-data)

*Please assign this to yourself if you are working on it so we're not stepping all over each other :)*

**Comment by acompa** [comment]
Potentially silly question: why not update the crontab in the Dockerfile? Something like

```
CMD (crontab -l ; echo "0 * * * * my_scraper_here") | sort - | uniq - | crontab -
```

(inspired by [this SO post](http://stackoverflow.com/a/13355743), which also ensures idempotency)

**Comment by WanderingStar** [comment]
@acompa, because crond isn't running inside the container, changing the crontab won't help.

I'm busy this afternoon, but if nobody has done this by this evening, I'll take a stab at it.

**Comment by hadoopjax** [comment]
Hey @WanderingStar if you think this is something you can tackle do you want to go ahead and assign the issue to yourself? My thinking was basically [this](https://gist.github.com/andyshinn/3ae01fa13cb64c9d36e7) but would be absolutely thrilled to have another person dig in :) we need all the hands we can get working on this stuff.

**Comment by WanderingStar** [comment]
I can't assign the issue to myself (because I'm not a contributor?) but I just created a pull request.

**Comment by hadoopjax** [comment]
Bah, ok. Running checks now!!

**Comment by WanderingStar** [comment]
@hadoopjax Note: the crontab in the PR just runs test.py, not the actual script. I didn't set up the AWS infrastructure to let me run the script.

**Comment by hadoopjax** [comment]
@WanderingStar no prob; changed around the auths (added twitter/aws) and pointed crontab to the relevant files and it worked perfectly. Thanks again for your help; hopefully we can talk you into doing some more stuff :)

**Comment by WanderingStar** [comment]
@hadoopjax Sure. I'm only a dabbler in data science, but I know a thing or two about software/systems.

**Comment by acompa** [comment]
@WanderingStar Thanks for the explanation! I figured the question would be silly. :) Happy to have a knowledgeable engineer on-board!
