### ISSUE TITLE
Change Tweet mapping in essetup.py

### ISSUE THREAD

**Issue by hadoopjax** [Data4Democracy/discursive#9]
Currently, the tweet mapping in [essetup.py](https://github.com/Data4Democracy/discursive/blob/master/essetup.py) does not match what is collected in index_twitter_*.py. This needs to match.

**Comment by ASRagab** [comment]
I could probably tackle this. Can it be assigned to me? Additionally, index_twitter_stream and index_twitter_search don't match each other, ought they to be in sync?

**Comment by hadoopjax** [comment]
Done - working on commit rights...soon :)

Yeah, all of them should be sync'd I just happened to see this one. I'd say go for it if you're opening up a PR for this one anyways.

**Comment by ASRagab** [comment]
https://github.com/Data4Democracy/discursive/pull/12

**Comment by ASRagab** [comment]
Can this be closed?

**Comment by hadoopjax** [comment]
Yep we're good it's in master. Thanks @ASRagab !!
